apiVersion: v1
kind: Service
metadata:
  name: codenet-language-classifier
spec:
  selector:
    app: codenet-language-classifier
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codenet-language-classifier
  labels:
    app: codenet-language-classifier
spec:
  selector:
    matchLabels:
      app: codenet-language-classifier
  replicas: 1
  template:
    metadata:
      labels:
        app: codenet-language-classifier
    spec:
      containers:
      - name: codenet-language-classifier
        image: quay.io/codait/codenet-language-classifier:latest
        ports:
        - containerPort: 5000
